      REAL DATA(18,16),CRIT(18),MEMBR(18),DISS(18)
      REAL CRITVAL(9)
      INTEGER IA(18),IB(18),ICHAIN(18),ICLASS(18,9),HVALS(9)
      INTEGER IORDER(9),HEIGHT(9)
      LOGICAL FLAG(18)
C
	OPEN(UNIT=21,STATUS='OLD',FILE='spectr.dat')
C
      N = 18
      M = 16
      DO I=1,N
        READ(21,100)(DATA(I,J),J=1,M)        
      ENDDO
 100  FORMAT(8F7.1)
      LEV = 9
C
C
      CALL HCON2(N,M,DATA,IA,IB,CRIT,MEMBR,DISS,ICHAIN,FLAG)
C
C
      CALL HCASS(N,IA,IB,CRIT,LEV,ICLASS,HVALS,IORDER,CRITVAL,HEIGHT)
C
C
      CALL HCDEN(LEV,IORDER,HEIGHT,CRITVAL)
C
C
      END
