      REAL DATA(18,16),CRIT(18),MEMBR(18)
      REAL CRITVAL(9)
      INTEGER IA(18),IB(18)
      INTEGER ICLASS(18,9),HVALS(9)
      INTEGER IORDER(9),HEIGHT(9)
      DIMENSION NN(18),DISNN(18)
      REAL D(153)
      LOGICAL FLAG(18)
C IN ABOVE, 18=N, 16=M, 9=LEV, 153=N(N-1)/2.
C
C
	OPEN(UNIT=21,STATUS='OLD',FILE='spectr.dat')
C
C
      N = 18
      M = 16
      DO I=1,N
        READ(21,100)(DATA(I,J),J=1,M)        
      ENDDO
 100  FORMAT(8F7.1)
C
C
      LEN = (N*(N-1))/2
      IOPT=1
      CALL HC(N,M,LEN,IOPT,DATA,IA,IB,CRIT,MEMBR,NN,DISNN,FLAG,D)
C
C
      LEV = 9
      CALL HCASS(N,IA,IB,CRIT,LEV,ICLASS,HVALS,IORDER,CRITVAL,HEIGHT)
C
C
      CALL HCDEN(LEV,IORDER,HEIGHT,CRITVAL)
C
C
      END
